### Get Products
GET http://localhost:3003/product

### Create Order
POST http://localhost:3003/order/create
Content-Type: application/json

{
    "userName": "Outro teste",
    "deliveryDate": "2023/04/15",
    "shoppingList": [
        {
            "productId": "19",
            "quantity": 910
        }
    ]
}

### Get Orders
GET  http://localhost:3003/order

### Get Order By Id
GET  http://localhost:3003/order/30f400b9-3952-4882-bef6-8fee059353f4
